create table posts(
    id numeric(10) primary key,
    author varchar(50) not null,
    title varchar(100) not null,
    d_date date not null default now(),
    resume varchar(100),
    content text not null
);

-- sequence
create SEQUENCE postsSequence increment by 1 start with 1;

-- strings should be escaped -> https://stackoverflow.com/questions/935/string-literals-and-escape-characters-in-postgresql
-- use: E'my String with \'
insert into posts (id, author, title, d_date, resume, content)
values(nextval('postsSequence'), 'sergioverde90@gmail.com', 'How to  build an +Angular 2 proyect', '08-09-2017', 'Ejemplo de cómo construir una aplicación +Angular 2 desde cero!', E'# Angular 2 + Angular CLI \n## Instalación de nodejs \nPrimero debemos tener instalado el gestor de paquetes npm y para ello necesitamos instalar nodejs \n> [nodejs](https://nodejs.org/es/download/) \n \n## Instalar angular CLI \n> npm install -g @angular/cli \n \nDejar instalando las dependencias. Probar sobre localhost:4200 \n \n## Instalar dependencia markdown \n> npm install ng2-markdown-to-html --save \n [markdown-to-html](https://www.npmjs.com/package/ng2-markdown-to-html) \n \n## Importar el módulo de markdown \n \n> import &#123; MarkdownToHtmlModule } from "ng2-markdown-to-html";  \n');

insert into posts (id, author, title, d_date, resume, content) 
values(nextval('postsSequence'), 'sergioverde90@gmail.com', 'CDI (Context and Dependency Injection) with @Transactional', '09-09-2017', 'Ejemplo de uso de la anotación @Transactional que provee la espcificación JTA', E'# Example with Docker, CDI and @Transactional annotation \nComplete example with a CDI and transactional resource. \n \nYou can test this example as follow: \n* Build war file \n```bash \nmvn clean install \n``` \n* Build the image \n```bash \ndocker build -t wildfly-cdi . \n``` \n* Run a container based in this image \n```bash \ndocker run -d --name cdi -p 8080:8080 wildfly-cdi \n``` \n* test the example \n```bash \ncurl -i http://localhost:8080/cdi-transactional/resources/cdi/tx \n```');

insert into posts (id, author, title, d_date, resume, content) 
values(nextval('postsSequence'), 'sergioverde90@gmail.com', 'Java CompletionService example', '09-09-2017', 'Llamadas asíncronas desde Java sin necesidad de ninguna librería de terceros', E'```java \npackage com.sergio.executors; \n \nimport java.util.ArrayList; \nimport java.util.List; \nimport java.util.concurrent.CompletionService; \nimport java.util.concurrent.ExecutionException; \nimport java.util.concurrent.ExecutorCompletionService; \nimport java.util.concurrent.Executors; \nimport java.util.concurrent.Future; \n \n/** \n * Created by Sergio on 01/03/2017. \n */ \npublic class CompletionServiceExample { \n \n    private static class Image { \n        private final long time; \n        private Image(long time) { \n            this.time = time; \n        } \n        private String download(){ \n            System.out.println(\"ETA \"+time / 1000 +\"/seconds ...\"); \n            try { \n                Thread.sleep(time); \n            } catch (InterruptedException e) { \n                e.printStackTrace(); \n            } \n \n            return time + \" image was donwloaded successfully\"; \n        } \n    }  \n \n public static void main(String[] args) { \n        List<Image> images = new ArrayList<>(); \n        images.add(new Image(6000)); \n        images.add(new Image(3000)); \n        images.add(new Image(1000)); \n \n        CompletionService<String> completionService = new ExecutorCompletionService<>( \n                Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors() * 2)); \n \n        images.forEach(i -> completionService.submit(i::download)); \n        \n        long start = System.nanoTime(); \n        images.forEach(i -> { \n            try { \n                Future<String> future = completionService.take(); \n                String downloaded = future.get(); \n                System.out.println(downloaded); \n            } catch (InterruptedException e) { \n                Thread.currentThread().interrupt(); \n            } catch (ExecutionException ee){ \n                throw new RuntimeException(ee.getCause()); \n            } \n        }); \n        long end = System.nanoTime(); \n        System.out.println(\"Finished all downloads in \" + (end-start) +\" / ns\"); \n    } \n} ```');